config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/latest",         to: "static_pages#latest"
  get "/follow",         to: "static_pages#follow"
  get "/follow/square",  to: "static_pages#follow_square"
  get "/help",           to: "static_pages#help"
  get "/about",          to: "static_pages#about"
  get "/terms",          to: "static_pages#terms"
  get "/privacy",        to: "static_pages#privacy"
  get "/test",           to: "static_pages#test"

  get  "/signup",   to: "users#new"
  post "/signup",   to: "users#create"
  get "/admusrind", to: "users#admusrind"

  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/auth/:provider/callback", to: "sessions#omniauth_create"

  get   "/welcome",    to: "settings#welcome"
  patch "/welcome",    to: "settings#welcome_update"
  put   "/welcome",    to: "settings#welcome_update"

  get  "/upload", to: "kicksposts#new"
  post "/upload", to: "kicksposts#create"

  get "/search", to: "searches#search"

  post   "/postcomments",    to: "comments#create"
  delete "/postcomment/:id", to: "comments#destroy",
                             as: "postcomment"

  resource :password_reset, except: [:show, :destroy],
                            path_names: { new: "" } do
    collection do
      get :confirm
    end
  end

  resource :contact, only: [:new],
                     path_names: { new: "" } do
    collection do
      post "/confirm", to: "contacts#sub_create"
      post "/",        to: "contacts#create"
      get  :confirm,
           :thanks
    end
  end

  resource   :notice,     only: [:show, :create, :destroy]
  resources  :goods,      only: [:create, :destroy]
  

  resources :users, param: :mysize_id,
                    only: [:index, :show, :destroy] do
    member do
      resources :kicksposts, except: [:new, :create, :index]

      get :following,
          :followers,
          :good
    end
  end

  resources :kicksposts, :comments, only: :none do
    get :gooders, on: :member
  end

  resources :relationships, only: [:create, :destroy]

  resource :settings, only: :none do
    get   "/option",   to: "settings#option"
    get   "/account",  to: "settings#account"
    get   "/profile",  to: "settings#profile"
    patch "/profile",  to: "settings#profile_update"
    put   "/profile",  to: "settings#profile_update"
    get   "/email",    to: "settings#email"
    patch "/email",    to: "settings#email_update"
    put   "/email",    to: "settings#email_update"
    get   "/mysizeid", to: "settings#mysizeid"
    patch "/mysizeid", to: "settings#mysizeid_update"
    put   "/mysizeid", to: "settings#mysizeid_update"
    get   "/password", to: "settings#password"
    patch "/password", to: "settings#password_update"
    put   "/password", to: "settings#password_update"
    get   "/leave",    to: "settings#leave"
    delete "/leave",   to: "settings#destroy"
  end

  # Engine to open mails in the browser
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:follow, :follow_square]
  before_action :setting_gon, only: [:latest, :follow, :follow_square]

  def home
    redirect_to latest_path if logged_in?
  end

  def latest
    @user = (logged_in? ? current_user : nil)
    @kicksposts = Kickspost.includes(:user, {comments: :user}, {goods: :gooder}).reorder(updated_at: :desc)
    @text = "short"
    gon.latestKicksposts = Kickspost.find_format_gon_params(@kicksposts.ids.uniq, @user)
    gon.currentUser = User.find_format_gon_params_by(@user&.id)
  end

  def follow
    @user = current_user
    @kicksposts = current_user.feed.includes(:user, {comments: :user}, {goods: :gooder}).reorder(updated_at: :desc)
    @text = "short"
    gon.followingKicksposts = Kickspost.find_format_gon_params(@kicksposts.ids.uniq, @user)
    gon.currentUser = User.find_format_gon_params_by(@user&.id)
  end

  def follow_square
    @user = current_user
    @kicksposts = current_user.feed.includes(:user, {comments: :user}, {goods: :gooder}).reorder(updated_at: :desc)
    @text = "short"
    gon.followingKicksposts = Kickspost.find_format_gon_params(@kicksposts.ids.uniq, @user)
    gon.currentUser = User.find_format_gon_params_by(@user&.id)
  end

  def help
  end

  def about
    flash.now[:danger] = "ログインまたは登録をお願いします。" if not_logged_in?
  end

  def terms
  end

  def privacy
  end

  def test
    gon.test = "Test!!!"
  end

  private

  def not_logged_in?
    !logged_in? && params[:about].in?(['on1', 'on2', 'on3'])
  end

  def setting_gon
    gon.currentInfo = {
      isLoggedIn: logged_in?,
      isPostPage: false
    }
  end
end

app/views/static_pages/_home_select.html.erb
<div class="select home-select c">
  <div class="container clear">
    <div class="select-list home-list alist aline">
      <%= link_to "新着", latest_path %>
    </div>
    <div class="select-list home-list alist aline">
      <%= link_to "フォロー中", follow_path %>
    </div>
    <div class="select-list home-list alist aline">
      <%= link_to "写真", follow_square_path %>
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "このサイトについて") %>
<% provide(:og_title, "このサイトについて") %>
<% provide(:og_url, about_url) %>
<%= render 'layouts/right_popup', icon: 'down' %>
<%= render 'layouts/left_popup' %>

<div class="container">
  <div class="content-sspace">
    <div class="ps-page-title c">
      <h1 class="about-title">
        <span class="logo-font about-logo">Mysize</span> とは
      </h1>
      <div class="about-title-icon">
        <%= image_tag('/images/apps_icon1.png', size: 110) %>
        <%= fa_icon('question') %>
      </div>
      <h2 class="about-mtitle">
        <p>スニーカー好きのための</p>
        <p>スニーカーに特化したSNSです</p>
      </h2>
    </div>
    <div class="about-main c">
      <p class="about-down">
        <a class="jump" data-scroll="-50" class="about-stitle" href="<%= about_path %>#about-can3">
          <%= fa_icon('hand-o-down') %>
        </a>
      </p>
      <div class="about-can"  id="about-can3">
        <h3 class="about-stitle">
          <a class="jump" data-scroll="-50" class="about-stitle" href="<%= about_path %>#about-can3">
            <span class="logo-font about-logo">Mysize</span>でできる３つのこと
          </a>
        </h3>
        <ul>
          <li>
            <a class="jump" data-scroll="-51" href="<%= about_path %>#about-post">
              <%= fa_icon('chevron-circle-right') %>マイスニーカーを簡単に記録して公開できる！
            </a>
          </li>
          <li>
            <a class="jump" data-scroll="-51" href="<%= about_path %>#about-search">
              <%= fa_icon('chevron-circle-right') %>欲しかったあのスニーカーのサイズ感がすぐに分かる！
            </a>
          </li>
          <li>
            <a class="jump" data-scroll="-51" href="<%= about_path %>#about-friend">
              <%= fa_icon('chevron-circle-right') %>スニーカー仲間の和を広げることができる！
            </a>
          </li>
        </ul>
      </div>
      <div class="about-list" id="about-post">
        <div class="about-icon">
          <%= fa_icon('archive') %>
          <%= fa_icon('plus') %>
        </div>
        <div class="about-text">
          <h4>マイスニーカーを<br>簡単に記録して公開できる！</h4>
          <div class="text">
            <p class="mb">あなたの愛用していたり、家の部屋や倉庫に眠っている大切なスニーカーはありませんか？</p>
            <p>せっかく手に入れた想い入れのあるスニーカーの</p>
            <p class="mb">感動や思い出も時間とともに色あせてしまっていませんか？</p>
            <p>Mysizeではあなたのスニーカーの</p>
            <p>『サイズ』をはじめ、</p>
            <p>『履き心地』や『履いていくおすすめシーン』、</p>
            <p>『手に入れたときのエピソード』に至るまで、</p>
            <p>あなたのスニーカーに関するあらゆることを</p>
            <p>写真と共に好きなように記録して</p>
            <p class="mb">手のひらに大切に保管しておくことができます！
            </p>
            <p>また、それを公開して共有することで、</p>
            <p>他の人からリアクションをもらえたり、</p>
            <p>同じスニーカーを手に入れたい人に情報を提供することで</p>
            <p class="mb">感謝してもらえたりするかもしれません！</p>
          </div>
        </div>
      </div>
      <div class="about-list" id="about-search">
        <div class="about-icon">
          <%= fa_icon('search') %>
          <%= fa_icon('question') %>
        </div>
        <div class="about-text">
          <h4>欲しかったあのスニーカーの<br>サイズ感がすぐに分かる！</h4>
          <div class="text">
            <p>スニーカーをオンラインやフリマサイトなどで</p>
            <p>購入しようとしたときに問題になってくるのが</p>
            <p class="mb">サイズ感が正確に分からないということです。</p>
            </p>
            <p>実際に試着できればいいのですが、</p>
            <p>店頭に行っても種類によっては完売していて試着できなかったり、</p>
            <p class="mb">そもそも店頭に行く手間も省きたかったりすることもあります。</p>
            <p>また、同じ種類のスニーカーでもカラーや製造年によってサイズ感にばらつきがあったりもして、</p>
            <p class="mb">一層、スニーカーのサイズ感を正確に知ることを困難にしています。</p>
            <p>そんなとき、ネットで検索して探したり、</p>
            <p>フリマサイトの出品者に質問したり、</p>
            <p>履いている仲間に聞いたりしていましたが、</p>
            <p class="mb">情報があちこちに分散していて、収集する手間も時間もかかってしまいます。。。</p>
            <p class="mb">それに、より正確に調べるために他のスニーカーのサイズ感も参考にしたくなったりもするでしょう。</p>
            <p>Mysizeではユーザー登録の際に</p>
            <p>スニーカーのベースサイズを登録してもらい、</p>
            <p class="mb">プロフィールにもベースにしているスニーカーの記載を推奨しています。</p>
            <p>また、スニーカーの投稿をする際にも</p>
            <p>必ずそのスニーカーのサイズを記録してもらっているので、</p>
            <p>ベースサイズや他のスニーカーのサイズと比較しながら、</p>
            <p>手に入れたいスニーカーのサイズ感を</p>
            <p>より正確に調べることができます。</p>
            <p class="mb sfont">(※必ずしも正確なサイズを保証するものではありません。)</p>
            <p>『Mysizeを見れば、欲しいスニーカーのサイズ感のことがすぐに分かる！』</p>
            <p class="mb">そんな場所を目指して、運営しています！</p>
          </div>
        </div>
      </div>
      <div class="about-list" id="about-friend">
        <div class="about-icon">
          <%= fa_icon('user') %>
          <%= fa_icon('handshake-o') %>
          <%= fa_icon('users') %>
        </div>
        <div class="about-text">
          <h4>スニーカー仲間の和を<br>広げることができる！</h4>
          <div class="text">
            <p>Mysizeはスニーカー好きな人たちが集まって</p>
            <p class="mb">スニーカーに関する様々なことを共有できる場です。</p>
            <p>サイズ感が同じ人や</p>
            <p>スニーカー争奪戦を共にした人、</p>
            <p>役に立つ情報を教えてくれる人や、</p>
            <p>自分と似た境遇の人など、</p>
            <p>この場所を通して、</p>
            <p>いろんなスニーカー好きな人たちを</p>
            <p class="mb">見つけることができるでしょう！</p>
            <p>見つけたら、その人をフォローしたり、</p>
            <p>かっこいいスニーカーや驚きのエピソード、</p>
            <p>役に立った情報には『グッド』ボタンで気持ちを伝えたり、</p>
            <p class="mb">コメントや質問をすることもできます。</p>
            <p>スニーカーという共通の趣味、生きがいを通して、</p>
            <p class="mb">交流を深めることで仲間の和を広げることができるかもしれません！</p>
          </div>
        </div>
      </div>
      <div class="about-lead" id="about-lead">
        <% if logged_in? %>
          <div class="c button-back button-mini">
            <a href="<%= root_path %>">
              <%= fa_icon("caret-left") %><span>TOPへ</span>
            </a>
          </div>
        <% else %>
          <div class="about-text">
            <h4>
              早速、<span class="logo-font about-logo">Mysize</span>を始めましょう！
            </h4>
          </div>
          <div class="c button button-large twitter-color">
            <%= link_to fa_icon("twitter") + t('views.login.twitter_register_or_login'), '/auth/twitter' %>
          </div>
          <div class="c button button-large accent">
            <%= link_to t('views.login.normal_register'), signup_path %>
          </div>
          <div class="c button mini-button waccent">
            <%= link_to fa_icon("sign-in") + t('views.login.normal_login'), login_path %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/follow.html.erb
<% provide(:title, "フォロー中") %>
<% provide(:og_title, "フォロー中") %>
<% provide(:og_url, follow_url) %>
<% content_for :javascript_addition do %>
  <%= javascript_include_tag "frontend/follow" %>
  <%= stylesheet_link_tag "frontend/follow", media: :all %>
<% end %>

<%= render partial: 'static_pages/home_logged_in',
           locals: { target: nil } %>

app/views/static_pages/follow_square.html.erb
<% provide(:title, "フォロー中") %>
<% provide(:og_title, "フォロー中") %>
<% provide(:og_url, follow_square_url) %>
<% content_for :javascript_addition do %>
  <%= javascript_include_tag "frontend/follow_square" %>
  <%= stylesheet_link_tag "frontend/follow_square", media: :all %>
<% end %>

<%= render 'home_select' %>
<div class="container">
  <div class="post-main">
    <% if @kicksposts.blank? %>
      <%= render partial: 'shared/no_data',
                 locals: { icon: 'image',
                           text: 'follow' } %>
    <% else %>
      <div class="post-line clear" data-react-entry="FollowingSquarePosts"></div>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <% title = "フォロー中" %>
  <% og_title = "フォロー中" %>
<% else %>
  <% title = "" %>
  <% og_title = "Mysize(マイサイズ) -スニーカーSNS-" %>
<% end %>
<% provide(:title, title) %>
<% provide(:og_title, og_title) %>
<% provide(:og_url, root_url) %>
<%= render 'layouts/left_popup' %>

<% if logged_in? %>
  <%= render partial: 'static_pages/home_logged_in',
             locals: { target: nil } %>
<% else %>
  <div class="container">
    <div class="content-fspace">
      <div class="page-title c">
        <div class="top-title c">
          <%= image_tag("/images/top-logo.png") %>
        </div>
      </div>
      <div class="top-main c" id="top-main">
        <h2 class="top-text"><%= raw t("views.static_pages.home.top-text") %></h2>
        <div class="top-lead">
          <div class="text" style="margin: 0;">
            <p><small><%= t("views.static_pages.home.top-lead") %></small></p>
            <p><%= fa_icon('hand-o-down') %></p>
          </div>
          <a class="about-stitle jump" data-scroll="-51" href="<%= about_path %>#about-can3">
            <span class="logo-font about-logo">Mysize</span>でできる３つのこと
          </a>
        </div>
      </div>
      <div class="c button button-large twitter-color">
        <%= link_to fa_icon("twitter") + t('views.login.twitter_register_or_login'), '/auth/twitter' %>
      </div>
      <div class="c button button-large accent">
        <%= link_to t('views.login.normal_register'), signup_path %>
      </div>
      <div class="c button mini-button waccent">
        <%= link_to fa_icon("sign-in") + t('views.login.normal_login'), login_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/static_pages/privacy.html.erb
<% provide(:title, "プライバシーポリシー") %>
<% provide(:og_title, "プライバシーポリシー") %>
<% provide(:og_url, privacy_url) %>

<div class="container">
  <div class="content-space">
    <div class="page-title">
      <h1 class="title-text">プライバシーポリシー</h1>
    </div>
    <div class="poricy">
      <p>
        マイサイズ運営事務局（以下「当社」といいます。）は、当社の提供するサービス（以下「本サービス」といいます。）における、ユーザーについての個人情報を含む利用者情報の取扱いについて、以下のとおりプライバシーポリシー（以下「本ポリシー」といいます。）を定めます。
      </p>

      <h2>1.　収集する利用者情報及び収集方法</h2>
      <p>
        本ポリシーにおいて、「利用者情報」とは、ユーザーの識別に係る情報、通信サービス上の光導履歴、その他ユーザーのスマートフォン、PC等の端末においてユーザーまたはユーザーの端末に関連して生成または蓄積された情報であって、本ポリシーに基づき当社が収集するものを意味するものとします。
      </p>

      <p>
        本サービスにおいて当社が収集する利用者情報は、その収集方法に応じて、以下のようなものとなります。
      </p>
      <p>(1)ユーザーからご提供いただく情報</p>
      <p>ユーザーが本サービスを利用するために、ご提供いただく情報は以下のとおりです。</p>
      <p>・氏名</p>
      <p>・メールアドレス</p>
      <p>・その他当社が定める入力フォームにユーザーが入力する情報</p>

      <p>(2)ユーザーが本サービスの利用において、他のサービスと連携を許可することにより、当該他のサービスからご提供いただく情報</p>
      <p>
        ユーザーが、本サービスを利用するにあたり、ソーシャルネットワークサービス等の外部サービスとの連携を許可した場合には、その許可の際にご提供いただきます。
      </p>
      <p>・当該外部サービスでユーザーが利用するID</p>
      <p>・その他当該外部サービスのプライバシー設定によりユーザーが連携先に開示を認めた情報</p>

      <p>(3)ユーザーが本サービスを利用するにあたって、当社が収集する情報</p>
      <p>
        当社は本サービスへのアクセス状況やその後利用方法に関する情報を収集することがあります。これには以下の情報が含まれます。
      </p>
      <p>・端末情報</p>
      <p>・ログ情報</p>
      <p>・Cookie及び匿名ID</p>
      <p>・位置情報</p>

      <h2>2.　利用目的</h2>
      <p>2-1　利用者情報は、2-2に定めるとおり本サービスの提供のために利用されるほか、2-3にあるとおり、その他の目的にも利用される場合があります。</p>
      <p>2-2　本サービスのサービス提供にかかわる利用者情報の具体的な利用目的は以下のとおりです。</p>
      <p>(1)本サービスに関する登録の受付、本人確認、利用料金の計算等本サービスの提供、維持、保護及び改善のため</p>
      <p>(2)本サービスに関するご案内、お問い合わせ等への対応のため</p>
      <p>(3)本サービスに関する当社の規約、ポリシー等（以下「規約等」といいます。）に違反する行為に対応するため</p>
      <p>(4)本サービスに関する規約等の変更などを通知するため</p>
      <p>(5)上記の利用目的に付随する利用目的のため</p>

      <p>2-3　上記2-2以外の利用目的は以下のとおりです。</p>
      <table>
        <tbody>
          <tr>
            <th>利用目的</th>
            <th>対応する利用者情報の項目</th>
          </tr>
          <tr>
            <th>(1)当社のサービスに関連して、個人を識別できない形式に加工した統計データを作成するため</th>
            <th>・端末情報・ログ情報・Cookie及び匿名ID・位置情報</th>
          </tr>
          <tr>
            <th>(2)当社または第三者の広告の配信または表示のため</th>
            <th>・端末情報・ログ情報・Cookie及び匿名ID・位置情報</th>
          </tr>
          <tr>
            <th>(3)その他マーケティングに利用するため</th>
            <th>・氏名・メールアドレス・その他当社が定める入力フォームにユーザーが入力する情報</th>
          </tr>
        </tbody>
      </table>

      <h2>3.　通知・公表または同意取得の方法、利用中止要請の方法</h2>
      <p>3-1　以下の利用者情報については、その収集が行われる前にユーザーの同意を得るものとします。</p>
      <p>(1)端末情報</p>
      <p>(2)位置情報</p>
      <p>
        3-2　ユーザーは、本サービスの所定の設定を行うことにより、利用者情報の全部または一部についてその利用の停止を求めることができ、この場合、当社は速やかに、当社の定めるところにした従い、その利用を停止します。なお利用者情報の項目によっては、その収集または利用が本サービスの前提となるため、当社所定の方法により本サービスを退会した場合に限り、当社はその収集を停止します。
      </p>

      <h2>4.　外部送信、第三者提供、情報収集モジュールの有無</h2>
      <p>
        利用者情報を利用したターゲティング広告の配信のため、本サービスには情報収集モジュールが組み込まれています。これに伴い、情報収集モジュール提供者への利用者情報の提供を行います。
      </p>
      <p>
        情報収集モジュール提供者に関しては「当サービス上における広告について(https://www.mysize.com/advertisement)」に記載しています。
      </p>

      <h2>5.　第三者提供</h2>
      <p>
        当社は、利用者情報のうち、個人情報については、個人情報保護法その他の法令に基づき開示が認められる場合を除くほか、あらかじめユーザーの同意を得ないで、第三者に提供しません。但し、次に掲げる場合はこの限りではありません。
      </p>
      <p>(1)当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</p>
      <p>(2)合併その他の事由による事業の継承に伴って個人情報が提供される場合</p>
      <p>(3)第４項の定めに従って、情報収集モジュール提供者へ個人情報が提供される場合</p>
      <p>(4)国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、ユーザーの同意を得ることによって当該事務の遂行に支障を及ぼすおそれがある場合</p>
      <p>(5)その他、個人情報保護法その他の法令で認められる場合</p>

      <h2>6.　個人情報の開示</h2>
      <p>
        当社は、ユーザーから、個人情報保護法の定めに基づき個人情報の開示を求められた時は、ユーザーご本人からのご請求であることを確認の上で、ユーザーに対し、遅滞なく開示を行います（当該個人情報が存在しないときにはその旨を通知いたします。）。但し、個人情報保護法その他の法令により、当社が開示の義務を負わない場合は、この限りではありません。なお、個人情報の開示につきましては、手数料(1件あたり2,000円)を頂戴しておりますので、あらかじめご了承ください。
      </p>

      <h2>7.　個人情報の訂正及び利用停止等</h2>
      <p>
        7-1　当社はユーザーから(1)個人情報が真実でないという理由によって個人情報保護法の定めに基づきその内容の訂正を求められた場合、及び(2)あらかじめ公表された利用目的の範囲を超えて取り扱われているという理由または偽りその他不正の手段により収集されたものであるという理由により、個人情報保護法の定めに基づきその利用の停止を求められた場合には、ユーザーご本人からのご請求であることを確認の上で遅滞なく必要な調査を行い、その結果に基づき、個人情報の内容の訂正または利用停止を行い、その旨をユーザーに通知します。なお、合理的な理由に基づいて訂正または利用停止を行わない旨の決定をしたときは、ユーザーに対しその旨を通知いたします。
      </p>
      <p>
        7-2　当社は、ユーザーから、ユーザーの個人情報について消去を求められた場合、当社が当該請求に応じる必要があると判断した場合は、ユーザーご本人からのご請求であることを確認の上で、個人情報の消去を行い、その旨をユーザーに通知します。
      </p>
      <p>
        7-3　個人情報保護法その他の法令により、当社が訂正等または利用停止等の義務を負わない場合は、前２項の規定は適用されません。
      </p>

      <h2>8.　お問い合わせ窓口</h2>
      <p>
        ご意見、ご質問、苦情のお申出その他利用者情報の取扱いに関するお問い合わせは、下記のページからお願い致します。
      </p>
      <p>マイサイズ運営事務局</p>
      <div class="attention">
        <p><%= link_to 'お問い合わせはこちら', contact_path %></p>
      </div>

      <h2>9.　プライバシーポリシーの変更手続</h2>
      <p>
        当社は、利用者情報の取扱いに関する運用状況を適宜見直し、継続的な改善に努めるものとし、必要に応じて、本ポリシーを変更することがあります。変更した場合にはWebサイト上でユーザーに通知いたします。但し、法令上ユーザーの同意が必要となるような内容の変更の場合は、当社所定の方法でユーザーの同意を得るものとします。
      </p>
      <div class="c button-back button-mini">
        <a href="<%= root_path %>">
          <%= fa_icon("caret-left") %><span>TOPへ</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/test.html.erb
<% content_for :javascript_addition do %>
  <%= javascript_include_tag "frontend/test" %>
<% end %>
<div data-react-entry="root"></div>