config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/latest",         to: "static_pages#latest"
  get "/follow",         to: "static_pages#follow"
  get "/follow/square",  to: "static_pages#follow_square"
  get "/help",           to: "static_pages#help"
  get "/about",          to: "static_pages#about"
  get "/terms",          to: "static_pages#terms"
  get "/privacy",        to: "static_pages#privacy"
  get "/test",           to: "static_pages#test"

  get  "/signup",   to: "users#new"
  post "/signup",   to: "users#create"
  get "/admusrind", to: "users#admusrind"

  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/auth/:provider/callback", to: "sessions#omniauth_create"

  get   "/welcome",    to: "settings#welcome"
  patch "/welcome",    to: "settings#welcome_update"
  put   "/welcome",    to: "settings#welcome_update"

  get  "/upload", to: "kicksposts#new"
  post "/upload", to: "kicksposts#create"

  get "/search", to: "searches#search"

  post   "/postcomments",    to: "comments#create"
  delete "/postcomment/:id", to: "comments#destroy",
                             as: "postcomment"

  resource :password_reset, except: [:show, :destroy],
                            path_names: { new: "" } do
    collection do
      get :confirm
    end
  end

  resource :contact, only: [:new],
                     path_names: { new: "" } do
    collection do
      post "/confirm", to: "contacts#sub_create"
      post "/",        to: "contacts#create"
      get  :confirm,
           :thanks
    end
  end

  resource   :notice,     only: [:show, :create, :destroy]
  resources  :goods,      only: [:create, :destroy]
  

  resources :users, param: :mysize_id,
                    only: [:index, :show, :destroy] do
    member do
      resources :kicksposts, except: [:new, :create, :index]

      get :following,
          :followers,
          :good
    end
  end

  resources :kicksposts, :comments, only: :none do
    get :gooders, on: :member
  end

  resources :relationships, only: [:create, :destroy]

  resource :settings, only: :none do
    get   "/option",   to: "settings#option"
    get   "/account",  to: "settings#account"
    get   "/profile",  to: "settings#profile"
    patch "/profile",  to: "settings#profile_update"
    put   "/profile",  to: "settings#profile_update"
    get   "/email",    to: "settings#email"
    patch "/email",    to: "settings#email_update"
    put   "/email",    to: "settings#email_update"
    get   "/mysizeid", to: "settings#mysizeid"
    patch "/mysizeid", to: "settings#mysizeid_update"
    put   "/mysizeid", to: "settings#mysizeid_update"
    get   "/password", to: "settings#password"
    patch "/password", to: "settings#password_update"
    put   "/password", to: "settings#password_update"
    get   "/leave",    to: "settings#leave"
    delete "/leave",   to: "settings#destroy"
  end

  # Engine to open mails in the browser
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_admin_post_main.html.erb
<% if type == 'Kickspost' %>
<li id="kickspost-<%= post.id %>" class="link-list kpost-main clear">
  <a class="content-link" href="<%= kickspost_path(post.user, post) %>"></a>
<% elsif type == 'Comment' %>
<li id="comment-<%= post.id %>" class="reply-<%= post.reply_id %> link-list kpost-main clear">
  <a class="content-link jump" data-scroll="-51" href="<%= kickspost_path(post.kickspost.user, post.kickspost) %>#<%= type.downcase %>-<%= post.id %>"></a>
<% end %>
  <div class="content-abs">
    <div class="content-height">
      <div class="list-content clear">
        <div class="c index-left kpost-left">
          <%= render partial: 'shared/index_left',
                     locals: { user: post.user } %>
        </div>
        <div class="kpost-center <%= type.downcase %>-center">
          <div class="kpost-name over-name">
            <%= link_to user_path(post.user) do %>
              <%= post.user.name %>
              <% if type == "Kickspost" %>
              <span> @<%= post.user.mysize_id %></span>
              <% else %>
              <span id="content-name-<%= post.id %>"> @<%= post.user.mysize_id %></span>
              <% end %>
            <% end %>
          </div>
          <% if type == "Kickspost" %>
            <div class="kpost-title">
              <h2><%= post.title %> <span>( <%= post.color %> )</span></h2>
            </div>
          <% end %>
          <% if  @text == "detail" %>
            <div class="kpost-content autolink">
              <span class="post-text"><%= post.content %></span>
            </div>
          <% else %>
            <div class="kpost-content autolink over-text">
              <span><%= post.content %></span>
            </div>
          <% end %>
        </div>
        <div class="kpost-act <%= type.downcase %>-act clear">
          <div class="kpost-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
        <div class="kpost-right <%= type.downcase %>-right">
          <div class="c kpost-right-top">
            <div class="kpost-menu <%= type.downcase %>-menu clear">
              <% if current_user.admin? %>
                <%= render partial: 'shared/post_menu',
                           locals: { post: post,
                                     type: type } %>
              <% end %>
            </div>
            <% if type == "Kickspost" %>
              <div class="kpost-picture abs-center">
                <%= link_to image_tag('/images/grey.gif',
                                      alt: post.title,
                                      class: 'cover lazyload',
                                      data: { src: picture_url(post) } ),
                            kickspost_path(post.user, post, display: 'picture') %>
                <div class="kpost-size index-size">
                  <%= post.size %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error">
    <div class="c error-title">
      入力内容をご確認ください。
    </div>
    <ul>
    <% object.errors.each do |key, message| %>
      <li><%= fa_icon("exclamation-circle") + message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_index_left.html.erb
<div class="index-image kpost-icon abs-center">
  <%= link_to image_tag(image_url(user), size: 40, alt: user.mysize_id),
              user_path(user, display: 'square'),
              class: "list-image" %>
  <div class="index-size kpost-shoesize">
    <span><%= user.size %></span>
  </div>
</div>

app/views/shared/_no_data.html.erb
<div class="c no-post">
  <% case icon
    when 'image' %>
    <%= fa_icon('image') %>
  <% when 'user' %>
    <%= fa_icon('user-o') %>
  <% when 'good' %>
    <%= fa_icon('thumbs-o-up') %>
  <% when 'search' %>
    <small><%= fa_icon('search') %></small>
  <% when 'notice' %>
    <%= fa_icon('bell-o') %>
  <% when 'develop' %>
    <%= fa_icon('wrench') %>
  <% else %>
    <%= fa_icon('question') %>
  <% end %>
  <div class="no-text">
    <% case text
      when 'search' %>
      <p>上のフォームより</p>
      <p>キーワードを入力してください</p>
    <% when 'search-no-hit' %>
      <p>検索結果は０件です</p><p>キーワードを確認してみてください</p>
    <% when 'notice' %>
      <p>１件もありません</p>
    <% when 'develop' %>
      <p>現在、開発中です</p><p>完成までいましばらくお待ちください</p>
    <% else %>
      <p>表示できるデータがありません</p>
      <% if logged_in? && current_user?(@user) %>
        <% case text
          when 'post', 'post-follow' %>
          <p>あなたのマイスニーカーについて投稿しましょう！</p>
          <% if text == 'post-follow' %>
            <p>フォローしてもらえるかもしれません！</p>
          <% end %>
          <div class="no-link">
            <a href="<%= upload_path %>">
              <%= fa_icon("plus-square") %><span>投稿する</span>
            </a>
          </div>
        <% when 'follow' %>
          <p>まずは、あなたと同じサイズの人を探して</p>
          <p>フォローしましょう！</p>
          <div class="no-link">
            <a href="<%= search_path(for: 'user', keyword: @user.size ) %>">
              <%= fa_icon("search") %><span>検索する</span>
            </a>
          </div>
        <% when 'good' %>
          <p>グッドはメモとしても使えます！</p>
          <p>キーワード検索をして役立つ情報には</p>
          <p>どんどんグッドをしましょう！</p>
          <div class="no-link">
            <a href="<%= search_path %>">
              <%= fa_icon("search") %><span>検索する</span>
            </a>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_no_data0.html.erb
<div class="c no-post">
  <% if target == "post" %>
    <%= fa_icon("image") %>
    <div class="no-text">表示できるデータがありません</div>
    <% if current_user?(user) %>
      <div class="no-text">あなたのマイスニーカーを投稿しましょう！</div>
      <div class="no-link">
        <a href="<%= upload_path %>">
          <%= fa_icon("plus-square") %><span>投稿する</span>
        </a>
      </div>
    <% end %>
  <% elsif target == "new" %>
    <%= fa_icon("image") %>
    <div class="no-text">表示できるデータがありません</div>
    <div class="no-text">まずはあなたと同じサイズの人を探して<br>フォローしましょう！</div>
    <div class="no-link">
      <a href="<%= search_path(for: 'user', keyword: user.size ) %>">
        <%= fa_icon("search") %><span>検索する</span>
      </a>
    </div>
  <% elsif target == "notice" %>
    <%= fa_icon("bell-o") %>
    <div class="no-text">１件もありません</div>
  <% elsif target == "person" %>
    <%= fa_icon("user-o") %>
    <div class="no-text">表示できるデータがありません</div>
    <% if current_user?(user) %>
      <div class="no-text">あなたと同じサイズの人を探して<br>フォローしましょう！</div>
      <div class="no-link">
        <a href="<%= search_path(for: 'user', keyword: user.size ) %>">
          <%= fa_icon("search") %><span>検索する</span>
        </a>
      </div>
    <% end %>
  <% elsif target == "good" %>
    <%= fa_icon("thumbs-o-up") %>
    <div class="no-text">表示できるデータがありません</div>
    <% if current_user?(user) %>
      <div class="no-text">グッドはメモとしても使えます<br>役立つ情報にはグッドをしましょう！</div>
      <div class="no-link">
        <a href="<%= search_path %>">
          <%= fa_icon("search") %><span>検索する</span>
        </a>
      </div>
    <% end %>
  <% elsif target == "development" %>
    <%= fa_icon("wrench") %>
    <div class="no-text">現在、開発中です<br>完成までいましばらくお待ちください</div>
  <% elsif target == "search" %>
    <%= fa_icon("search") %>
    <div class="no-text">キーワードを入力してください</div>
  <% else %>
    <div class="no-text">表示できるデータがありません</div>
  <% end %>
</div>

app/views/shared/_post_delete.html.erb
<% if type == "Comment" %>
  <% post_delete_url = postcomment_url(post.id, kickspost_id: post.kickspost_id) %>
<% else %>
  <% post_delete_url =  kickspost_url(post.user.mysize_id, post) %>
<% end %>

<%= link_to fa_icon("trash") + " 投稿を削除する",
            post_delete_url,
            method: :delete,
            data: { confirm: "本当に削除してよろしいですか？" } %>

app/views/shared/_post_main.html.erb
<% if type == 'Kickspost' %>
<li id="kickspost-<%= post.id %>" class="link-list kpost-main clear">
  <a class="content-link" href="<%= kickspost_path(post.user, post) %>"></a>
<% elsif type == 'Comment' %>
<li id="comment-<%= post.id %>" class="reply-<%= post.reply_id %> link-list kpost-main clear">
  <a class="content-link jump" data-scroll="-51" href="<%= kickspost_path(post.kickspost.user, post.kickspost) %>#<%= type.downcase %>-<%= post.id %>"></a>
<% end %>
  <div class="content-abs">
    <div class="content-height">
      <% unless reply_on %>
      <div class="list-content clear">
      <% else %>
      <div class="list-content reply-main clear">
      <% end %>
        <% if reply_on %>
          <div class="c kpost-reply-icon">
            <%= fa_icon("caret-right") %>
          </div>
        <% end %>
        <div class="c index-left kpost-left">
          <%= render partial: 'shared/index_left',
                     locals: { user: post.user } %>
        </div>
        <div class="kpost-center <%= type.downcase %>-center">
          <div class="kpost-name over-name">
            <%= link_to user_path(post.user) do %>
              <%= post.user.name %>
              <% if type == "Kickspost" %>
                <span> @<%= post.user.mysize_id %></span>
              <% else %>
                <span id="content-name-<%= post.id %>"> @<%= post.user.mysize_id %></span>
              <% end %>
            <% end %>
          </div>
          <% if type == "Kickspost" %>
            <div class="kpost-brand">
              <span><%= post.brand %></span>
            </div>
            <div class="kpost-title">
              <h2><%= post.title %> <span>( <%= post.color %> )</span></h2>
            </div>
          <% end %>
          <% if  @text == "detail" %>
            <div class="kpost-content autolink">
              <span class="post-text"><%= post.content %></span>
            </div>
          <% else %>
            <div class="kpost-content autolink over-text">
              <span><%= post.content %></span>
            </div>
          <% end %>
        </div>
      <% if reply_on %>
      <div class="kpost-act  <%= type.downcase %>-act reply-act clear">
      <% else %>
      <div class="kpost-act  <%= type.downcase %>-act clear">
      <% end %>
        <div class="kpost-time">
          <%= time_ago_in_words(post.created_at) %>前
        </div>
        <div class="kpost-alist">
          <div class="kpost-aicon">
            <%= render partial: 'goods/good_form',
                       locals: { post: post,
                                 type: type } %>
          </div>
          <div class="kpost-num" id="good-num-<%= type.underscore %>-<%= post.id %>">
            <% if type == 'Kickspost' %>
              <%= link_to post.goods.size, gooders_kickspost_path(post) %>
            <% else %>
              <%= link_to post.goods.size, gooders_comment_path(post) %>
            <% end %>
          </div>
        </div>
        <% if type == "Kickspost" %>
          <div class="kpost-alist">
            <%= link_to kickspost_path(post.user, post), class: "kpost-alink" do %>
              <div class="kpost-aicon">
                <%= fa_icon("comment-o") %>
              </div>
              <div class="kpost-num">
                <span><%= post.comments.size %></span>
              </div>
            <% end %>
          </div>
          <div class="kpost-alist alist-last">
            <%= link_to "https://twitter.com/intent/tweet?text=" +
                ERB::Util.url_encode(post.user.name + "さんの投稿｜" +
                                     post.title + "\n") +
                "&url=" + kickspost_url(post.user, post),
                class: "kpost-alink",
                onclick: "window.open(encodeURI(decodeURI(this.href)), 'tweetwindow', 'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1'); return false;" do %>
              <div class="kpost-aicon">
                <%= fa_icon('twitter') %>
              </div>
            <% end %>
          </div>
        <% end %>
        <% if type == "Comment" && current_user != post.user %>
          <div class="kpost-alist alist-last">
            <div class="kpost-aicon" id="comment-reply-<%= post.id %>">
              <% if post_page %>
                <%= fa_icon('reply')%>
              <% elsif logged_in? %>
                <a class="kpost-alink jump" data-scroll="-51" href="<%= kickspost_path(post.kickspost.user, post.kickspost, reply: 'on') %>#<%= type.downcase %>-<%= post.id %>">
                  <%= fa_icon('reply')%>
                </a>
              <% else%>
                <%= link_to fa_icon('reply'), '#', class: 'ban' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="kpost-right <%= type.downcase %>-right">
        <div class="c kpost-right-top">
          <div class="kpost-menu  <%= type.downcase %>-menu clear">
            <% if current_user == post.user %>
              <%= render partial: 'shared/post_menu',
                         locals: { post: post,
                                   type: type } %>
            <% end %>
          </div>
          <% if type == "Kickspost" %>
            <div class="kpost-picture abs-center">
              <%= link_to image_tag('/images/grey.gif',
                                    alt: post.title,
                                    class: 'cover lazyload',
                                    data: { src: picture_url(post) } ),
                          kickspost_path(post.user, post, display: 'picture') %>
              <div class="kpost-size index-size">
                <%= post.size %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/shared/_post_menu.html.erb
<div id="post-nav-<%= type.underscore %>-<%= post.id %>" class="post-nav">
  <%= fa_icon("angle-down") %>
</div>
<ul id="nav-list-<%= type.underscore %>-<%= post.id %>" class="nav-list">
  <li>
    <%= render partial: 'shared/post_delete',
               locals: { post: post,
                         type: type } %>
  </li>
  <% if type == "Kickspost" %>
  <li class="bar"></li>
  <li>
    <%= link_to fa_icon("pencil-square-o") + " 投稿を編集する",
                edit_kickspost_path(post.user.mysize_id, post) %>
  </li>
  <li class="bar"></li>
  <li>
    <%= link_to fa_icon("twitter") + " Twitterでシェア",
                "https://twitter.com/intent/tweet?text=" +
                ERB::Util.url_encode(post.user.name + "さんの投稿｜" +
                                     post.title + "\n") +
                "&url=" + kickspost_url(post.user, post),
                class: "kpost-alink",
                onclick: "window.open(encodeURI(decodeURI(this.href)), 'tweetwindow', 'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1'); return false;" %>
  </li>
  <% end %>
</ul>

app/views/shared/_search_form.html.erb
<div class="c inner-form search-form container clear">
  <%= form_tag(yield(:search_url),
               method: "get",
               enforce_utf8: false) do %>
    <% if params[:for].blank? %>
      <div><%= hidden_field_tag :for, "post" %></div>
    <% else %>
      <div><%= hidden_field_tag :for, params[:for] %></div>
    <% end %>
    <%= text_field_tag :keyword, params[:keyword],
                        placeholder: "キーワード検索" %>
    <div class="inner-button search-button">
      <%= button_tag fa_icon("search"), name: nil %>
    </div>
  <% end %>
</div>

app/views/shared/gooders.html.erb
<% provide(:title, "グッドしたユーザー") %>
<% provide(:og_title, "グッドしたユーザー") %>
<% provide(:og_url, @url) %>
<%= render 'layouts/back', back_path: "#{kickspost_path(@main.user, @main)}" %>
<%= render 'layouts/center_header', header_text: "グッドしたユーザー" %>

<div class="container content-nspace">
  <% unless @users.blank? %>
    <div class="setting-select">
      <ul>
        <%= render @users %>
      </ul>
    </div>
  <% else %>
    <%= render partial: 'shared/no_data',
               locals: { icon: 'user',
                         text: nil } %>
  <% end %>
</div>