config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/latest",         to: "static_pages#latest"
  get "/follow",         to: "static_pages#follow"
  get "/follow/square",  to: "static_pages#follow_square"
  get "/help",           to: "static_pages#help"
  get "/about",          to: "static_pages#about"
  get "/terms",          to: "static_pages#terms"
  get "/privacy",        to: "static_pages#privacy"
  get "/test",           to: "static_pages#test"

  get  "/signup",   to: "users#new"
  post "/signup",   to: "users#create"
  get "/admusrind", to: "users#admusrind"

  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/auth/:provider/callback", to: "sessions#omniauth_create"

  get   "/welcome",    to: "settings#welcome"
  patch "/welcome",    to: "settings#welcome_update"
  put   "/welcome",    to: "settings#welcome_update"

  get  "/upload", to: "kicksposts#new"
  post "/upload", to: "kicksposts#create"

  get "/search", to: "searches#search"

  post   "/postcomments",    to: "comments#create"
  delete "/postcomment/:id", to: "comments#destroy",
                             as: "postcomment"

  resource :password_reset, except: [:show, :destroy],
                            path_names: { new: "" } do
    collection do
      get :confirm
    end
  end

  resource :contact, only: [:new],
                     path_names: { new: "" } do
    collection do
      post "/confirm", to: "contacts#sub_create"
      post "/",        to: "contacts#create"
      get  :confirm,
           :thanks
    end
  end

  resource   :notice,     only: [:show, :create, :destroy]
  resources  :goods,      only: [:create, :destroy]
  

  resources :users, param: :mysize_id,
                    only: [:index, :show, :destroy] do
    member do
      resources :kicksposts, except: [:new, :create, :index]

      get :following,
          :followers,
          :good
    end
  end

  resources :kicksposts, :comments, only: :none do
    get :gooders, on: :member
  end

  resources :relationships, only: [:create, :destroy]

  resource :settings, only: :none do
    get   "/option",   to: "settings#option"
    get   "/account",  to: "settings#account"
    get   "/profile",  to: "settings#profile"
    patch "/profile",  to: "settings#profile_update"
    put   "/profile",  to: "settings#profile_update"
    get   "/email",    to: "settings#email"
    patch "/email",    to: "settings#email_update"
    put   "/email",    to: "settings#email_update"
    get   "/mysizeid", to: "settings#mysizeid"
    patch "/mysizeid", to: "settings#mysizeid_update"
    put   "/mysizeid", to: "settings#mysizeid_update"
    get   "/password", to: "settings#password"
    patch "/password", to: "settings#password_update"
    put   "/password", to: "settings#password_update"
    get   "/leave",    to: "settings#leave"
    delete "/leave",   to: "settings#destroy"
  end

  # Engine to open mails in the browser
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/kickspost.rb
class Kickspost < ApplicationRecord
  extend Search

  search_fields :title, :color, :brand, :content, size_field: :size
  
  belongs_to :user
  has_many   :comments, dependent:  :destroy
  has_many   :goods,    as:         :post,
                        dependent:  :destroy,
                        class_name: "Good"
  has_many   :gooders,  through:    :goods,
                        source:     :gooder
  has_one    :notice,   as:         :kind,
                        dependent:  :destroy,
                        class_name: "Notice"

  default_scope -> { order(created_at: :desc) }

  mount_uploader :picture, PictureUploader

  validates :user_id, presence: { message: "ユーザーを特定できません" }
  validates :title,   presence: { message: "スニーカー名を入力してください" },
                      length:   { maximum: 50,
                                  message: "スニーカー名は最大50文字まで入力できます" }
  validates :color,   presence: { message: "カラーを選択して下さい" },
                      length:   { maximum: 30,
                                  message: "カラーは最大30文字まで入力できます" }
  validates :brand,   presence: { message: "ブランドを選択して下さい" },
                      length:   { maximum: 30,
                                  message: "ブランドは最大30文字まで入力できます" }
  validates :content, presence: { message: "内容を入力してください" },
                      length:   { maximum: 500,
                                  massage: "500文字まで入力できます" }
  validates :picture, presence: { message: "ファイルを選択してください",
                                  on: :create }
  validate  :picture_size
  validates :size,    presence: { message: "スニーカーのサイズを選択してください" }

  class << self
    def all_format_gon_params_for(cuser)
      self.all.map do |post|
        map_gon_hah(post, cuser)
      end
    end

    def find_format_gon_params(ids, cuser)
      self.find(ids).map do |post|
        map_gon_hah(post, cuser)
      end
    end

    def find_format_gon_params_by(id, cuser)
      return if id.nil?
      map_gon_hah(self.find_by(id: id), cuser)
    end

    private

    def extract_params_for_gon
      [:id, :user_id, :brand, :color, :title, :content, :size, :created_at, :picture_url]
    end

    def map_gon_hah(post, cuser)
      return if post.blank?
      post_type = post.class.name.downcase
      if cuser.present?
        is_good = cuser.good?(post_type, post)
        post_good = cuser.active_goods.find_by(post_type: post_type, post_id: post.id)
      else
        is_good = false
        post_good = nil
      end

      Hash[
        extract_params_for_gon.map do |ep|
          [ep, post.send(ep)]
        end
      ].merge({
        postType: post_type,
        postUser: User.find_format_gon_params_by(post&.user_id),
        goodNum: post.goods.size,
        commentNum: post.comments.size,
        isGood: is_good,
        isMyPost: cuser == post.user,
        goodId: post_good.present? ? post_good.id : post_good
      })
    end
  end

  def good_notice_create_or_update
    return create_notice(user_id: self.user_id) if self.notice.nil?
    notice.add_unread_count!
  end

  def good_notice_check_or_delete
    return if self.goods.any? || !(good_notice = self.notice)
    good_notice.destroy
  end

  def mysize_ids
    content.scan(/@[a-zA-Z0-9_]+/).map {|id| id.delete("@")}
  end

  def is_reply?
    mysize_ids.any?
  end

  def extract_others_replied_by(mysize_id, cuser)
    return nil if mysize_id == cuser.mysize_id
    User.find_by(mysize_id: mysize_id)
  end

  def create_notice_to_others_from(cuser)
    mysize_ids.each do |msid|
      other = self.extract_others_replied_by(msid, cuser)
      next if other.nil?
      other.receive_notice_of("ReplyPost", self) 
    end
  end

  def delete_notice_from_others_by(cuser)
    mysize_ids.each do |msid|
      other = self.extract_others_replied_by(msid, cuser)
      next if other.nil?
      other.lose_notice_of("ReplyPost", self)
    end
  end

  def gooders_without(user)
    gooders.where.not(id: user.id)
  end

  private

  def picture_size
    error.add(:picture, "画像サイズは最大5MBまで設定できます") if picture.size > 5.megabytes
  end
end

app/controllers/kicksposts_controller.rb
class KickspostsController < ApplicationController
  before_action :logged_in_user, except: [:show]

  def show
    @kickspost = Kickspost.find_by(id: params[:id])
    @user = @kickspost.user
    redirect_to kickspost_path(@user, @kickspost) if @user.mysize_id != params[:mysize_id]

    @comments = @kickspost.comments.includes(:user, :goods, :replies).where(reply_id: 0)
    @text = "detail"
  end

  def new
    @kickspost = current_user.kicksposts.build
  end

  def create
    @kickspost = current_user.kicksposts.build(kickspost_params)
    if @kickspost.save
      @kickspost.create_notice_to_others_from(current_user) if @kickspost.is_reply?
      flash[:success] = "投稿に成功しました"
      redirect_to follow_url
    else
      render 'new'
    end
  end

  def edit
    @kickspost = Kickspost.find_by(id: params[:id])
    @user = @kickspost.user
    redirect_if_invalid(@user)
    redirect_to kickspost_path(@user, @kickspost) if @user.mysize_id != params[:mysize_id]
  end

  def update
    @kickspost = Kickspost.find_by(id: params[:id])
    @user = @kickspost.user
    redirect_if_invalid(@user)
    redirect_to kickspost_path(@user, @kickspost) and return if @user.mysize_id != params[:mysize_id]

    if @kickspost.update_attributes(kickspost_params)
      flash[:success] = "編集に成功しました"
      redirect_to follow_url
    else
      render 'edit'
    end
  end

  def destroy
    @kickspost = Kickspost.find_by(id: params[:id])
    @user = @kickspost.user
    redirect_if_invalid(@user) and return
    redirect_to kickspost_path(@user, @kickspost) and return if @user.mysize_id != params[:mysize_id]

    @kickspost.comments.each do |comment|
      comment.delete_notice_from_others_and(current_user, current_user) if comment.is_reply?
      comment.delete_comment_notice_from(current_user, current_user)
    end

    @kickspost.delete_notice_from_others_by(current_user) if @kickspost.is_reply?

    @kickspost.destroy
    flash[:danger] = "投稿を削除しました"
    redirect_to user_path(current_user, display: "square")
  end

  def gooders
    @post = Kickspost.find_by(id: params[:id])
    @main = @post
    @users = @post.gooders.all
    @url = gooders_kickspost_url(@post)
    render 'shared/gooders'
  end

  private

  def kickspost_params
    params.require(:kickspost).permit(:title, :color, :brand,
                                      :content, :picture,
                                      :picture_cache, :size)
  end

  def redirect_if_invalid(user)
    return if current_user?(user) || current_user.admin?
    flash[:danger] = "権限がありません"
    redirect_to(root_url) and return true
  end
end

app/helpers/kicksposts_helper.rb
module KickspostsHelper

  def picture_url(post)
    if post.picture?
      "#{post.picture}"
    else
      "/images/default1.png"
    end
  end
end

app/views/kicksposts/_kickspost.html.erb
<% if params[:display] == "square" %>
  <li id="square-<%= kickspost.id %>" class="square-list">
    <div class="square-picture">
      <%= link_to image_tag('/images/grey.gif', alt: kickspost.title,
                        class: 'cover lazyload', data: { src: picture_url(kickspost) } ),
                        kickspost_path(kickspost.user, kickspost) %>
    </div>
    <div class="square-size">
      <%= kickspost.size %>
    </div>
  </li>
<% else %>
  <%= render partial: 'shared/post_main',
             locals: { post: kickspost,
                       type: 'Kickspost',
                       reply_on: false,
                       post_page: post_page } %>
<% end %>

app/views/kicksposts/_kickspost_picture.html.erb
<div id="kickspost-<%= kickspost.id %>" class="kickspost-list">
  <div class="ppost-top">
    <div class="ppost-icon">
      <%= link_to image_tag(image_url(kickspost.user), size: 34,
                            alt: kickspost.user.mysize_id),
                  user_path(kickspost.user) %>
    </div>
    <div class="c ppost-usize">
      <%= link_to kickspost.user.size,
                  user_path(kickspost.user) %>
    </div>
    <div class="ppost-prof">
      <div class="ppost-name over-name">
        <%= link_to kickspost.user.name, user_path(kickspost.user) %>
      </div>
      <div class="ppost-msid">
        <%= link_to "@" + kickspost.user.mysize_id, user_path(kickspost.user) %>
      </div>
    </div>
    <div class="post-menu c">
      <% if current_user == kickspost.user %>
        <%= render partial: 'shared/post_menu',
                   locals: { post: kickspost,
                             type: "Kickspost" } %>
      <% end %>
    </div>
  </div>
  <div class="ppost-middle">
    <div class="ppost-main">
      <div class="ppost-picture">
        <%= link_to image_tag('/images/grey.gif', alt: kickspost.title,
                    class: 'lazyload', data: { src: picture_url(kickspost) } ),
                    kickspost_path(kickspost.user, kickspost) %>
      </div>
      <div class="ppost-ksize c">
        <%= kickspost.size %>
      </div>
    </div>
    <div class="ppost-act">
      <div class="good-act c">
        <%= render partial: 'goods/good_form',
                   locals: { post: kickspost,
                             type: "Kickspost" } %>
      </div>
      <div class="ppost-num c">
        <div class="ppost-good-num" id="good-num-kickspost-<%= kickspost.id %>">
          <%= link_to kickspost.goods.size,
                      gooders_kickspost_path(kickspost) %>
        </div>
      </div>
      <div class="comment-act c">
        <%= link_to fa_icon("comment-o"),
                    kickspost_path(kickspost.user, kickspost) %>
      </div>
      <div class="ppost-num c">
        <div class="ppost-good-num">
          <%= link_to kickspost.comments.size,
                      kickspost_path(kickspost.user, kickspost)  %>
        </div>
      </div>
      <div class="twitter-act c">
        <%= link_to "https://twitter.com/intent/tweet?text=" +
            ERB::Util.url_encode(kickspost.user.name + "さんの投稿｜" +
                                 kickspost.title + "\n") +
            "&url=" + kickspost_url(kickspost.user, kickspost),
            class: "kpost-alink", 
            onclick: "window.open(encodeURI(decodeURI(this.href)), 'tweetwindow', 'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1'); return false;" do %>
          <%= fa_icon('twitter') %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="ppost-bottom">
    <div class="kpost-brand">
      <span><%= kickspost.brand %></span>
    </div>
    <div class="ppost-title">
      <h2><%= kickspost.title %> <span>( <%= kickspost.color %> )</span></h2>
    </div>
    <div class="ppost-content autolink">
      <%= link_to kickspost.user.mysize_id,
                  user_path(kickspost.user),
                  class: 'content-name' %>
      <span class="post-text"><%= kickspost.content %></span>
    </div>
    <div class="ppost-time">
      <span><%= time_ago_in_words(kickspost.created_at) %>前</span>
    </div>
    <% unless kickspost.comments.blank? %>
      <div class="post-comment">
        <% if comment_disnum == "few" %>
          <div class="comment-lead">
            <% if current_user == kickspost.user %>
              <%= link_to "コメントを見る・返信する",
                  kickspost_path(kickspost.user, kickspost) %>
            <% else %>
              <%= link_to "コメントを見る・書く",
                  kickspost_path(kickspost.user, kickspost) %>
            <% end %>
          </div>
        <% end %>
        <ul>
          <% if comment_disnum == "few" %>
            <%= render partial: 'comments/comment',
                       locals: { kickspost: kickspost,
                                 comment: kickspost.comments.first,
                                 comment_disnum: comment_disnum,
                                 list: "line" } %>
          <% else %>
            <%= render partial: @comments,
                       locals: { kickspost: kickspost,
                                 comment_disnum: comment_disnum,
                                 list: "line" } %>
          <% end %>
        </ul>
      </div>
    <% else %>
      <% if comment_disnum == "few" && current_user != kickspost.user %>
        <div class="comment-lead">
          <%= link_to "コメントを書く",
            kickspost_path(kickspost.user, kickspost) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/kicksposts/edit.html.erb
<% provide(:title, "キックスポスト編集") %>
<% provide(:og_title, "キックスポスト編集") %>
<% provide(:og_url, edit_kickspost_url(@kickspost.user, @kickspost)) %>

<div class="container content-fspace">
  <div class="post-form">
    <%= form_for(@kickspost,
                 url: kickspost_path(@kickspost.user, @kickspost),
                 multipart: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="set-form clear">
        <div class="upload-form">
          <div class="label-form file-label">
            <%= f.label :picture, "画像" %>
          </div>
          <div class="file-form">
            <%= f.label :picture, class: "upload-button" do %>
          <div class="upload-icon">
            <% if @kickspost.picture.blank? %>
              <%= fa_icon("plus") %>
            <% else %>
              <%= fa_icon("refresh") %>
            <% end %>
          </div>
          <% if @kickspost.picture.blank? %>
            <div class="preview"></div>
          <% else %>
            <div class="preview"><%= image_tag(picture_url(@kickspost), alt: @kickspost.content, class: "cover") %></div>
          <% end %>
        <% end %>
          </div>
          <div class="base-form hidden-form">
            <%= f.file_field :picture %>
            <%= f.hidden_field :picture_cache %>
          </div>
        </div>
        <div class="size-form">
          <div class="label-form select-label">
            <%= f.label :size, "スニーカーのサイズ" %>
          </div>
          <div class="base-form select-form">
            <%= f.select(:size, options_for_select(size_array, @kickspost.size)) %>
            <div class="c select-icon"><%= fa_icon("chevron-down") %></div>
          </div>
        </div>
      </div>
      <div class="label-form">
        <%= f.label :brand, "ブランド" %>
      </div>
      <div class="base-form">
        <%= f.text_field :brand, placeholder: "例) Adidas, Nike ×　Supreme" %>
      </div>
      <div class="label-form">
        <%= f.label :title, "スニーカー名" %>
      </div>
      <div class="base-form">
        <%= f.text_field :title, placeholder: "例) Air Jordan 1" %>
      </div>
      <div class="label-form">
        <%= f.label :color, "カラー" %>
      </div>
      <div class="base-form">
        <%= f.text_field :color, placeholder: "例) Black, White/Red" %>
      </div>
      <div class="label-form">
        <%= f.label :content, "投稿フォーム" %>
      </div>
      <div class="base-form base-form-area">
        <%= f.text_area :content, class: "autoheight text-area",
                        placeholder: "スニーカーのサイズ感や履き心地、エピソードなど好きなように投稿しましょう！(500文字以内)\n\nハッシュタグも付けられます！\n(#nike #airmax ...)" %>
      </div>
      <div class="c button button-mini accent">
        <%= f.submit "更新", data: { disable_with: "処理中..."} %>
      </div>
      <script type="text/javascript">
        $('#kickspost_picture').bind('change', function() {
          var size_in_megabytes = this.file[0].size/1024/1024;
          if (size_in_megabytes > 5) {
            alert('ファイルは最大5MBまでとなります。');
          }
        });
      </script>
    <% end %>
  </div>
</div>

app/views/kicksposts/new.html.erb
<% provide(:title, "投稿作成") %>
<% provide(:og_title, "投稿作成") %>
<% provide(:og_url, upload_url) %>
<%= render 'layouts/back', back_path: "#{user_path(current_user)}" %>
<%= render 'layouts/center_header', header_text: "投稿作成" %>

<div class="container content-fspace">
  <div class="post-form">
    <%= form_for(@kickspost, url: upload_path, multipart: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="set-form clear">
        <div class="upload-form">
          <div class="label-form file-label">
            <%= f.label :picture, "画像" %>
          </div>
          <div class="file-form">
            <%= f.label :picture, class: "upload-button" do %>
              <div class="upload-icon">
                <%= fa_icon("plus") %>
              </div>
              <div class="preview"></div>
            <% end %>
          </div>
          <div class="base-form hidden-form">
            <%= f.file_field :picture %>
            <%= f.hidden_field :picture_cache %>
          </div>
        </div>
        <div class="size-form">
          <div class="label-form select-label">
            <%= f.label :size, "スニーカーのサイズ" %>
          </div>
          <div class="base-form select-form">
            <%= f.select(:size, options_for_select(size_array), prompt: "選 択") %>
            <div class="c select-icon"><%= fa_icon("chevron-down") %></div>
          </div>
        </div>
      </div>
      <div class="label-form">
        <%= f.label :brand, "ブランド" %>
      </div>
      <div class="base-form">
        <%= f.text_field :brand, placeholder: "例) Adidas, Nike × Supreme" %>
      </div>
      <div class="label-form">
        <%= f.label :title, "スニーカー名" %>
      </div>
      <div class="base-form">
        <%= f.text_field :title, placeholder: "例) Air Jordan 1" %>
      </div>
      <div class="label-form">
        <%= f.label :color, "カラー" %>
      </div>
      <div class="base-form">
        <%= f.text_field :color, placeholder: "例) Black, White/Red" %>
      </div>
      <div class="label-form">
        <%= f.label :content, "投稿フォーム" %>
      </div>
      <div class="base-form base-form-area">
        <%= f.text_area :content, class: "autoheight text-area",
          placeholder: "スニーカーのサイズ感や履き心地、エピソードなど好きなように投稿しましょう！(500文字以内)\n\nハッシュタグも付けられます！\n(#nike #airmax ...)" %>
      </div>
      <div class="c button button-mini accent">
        <%= f.submit "投稿する", data: { disable_with: "処理中..."} %>
      </div>
      <script type="text/javascript">
        $('#kickspost_picture').bind('change', function() {
          var size_in_megabytes = this.file[0].size/1024/1024;
          if (size_in_megabytes > 5) {
            alert('ファイルは最大5MBまでとなります。');
          }
        });
      </script>
    <% end %>
  </div>
</div>

app/views/kicksposts/show.html.erb
<% provide(:title, @user.name + "(@" + @user.mysize_id + ")さんの投稿") %>
<% provide(:og_title, @user.name + "(@" + @user.mysize_id + ")さんの投稿") %>
<% provide(:og_url, kickspost_url(@kickspost.user, @kickspost)) %>


<div class="c select kpost-select">
  <div class="container clear">
    <div class="select-list kpost-list alist aline" id="reply-active">
      <%= link_to "テキスト",
          kickspost_path(@kickspost.user, @kickspost) %>
    </div>
    <div class="select-list kpost-list alist aline">
      <%= link_to "写真",
          kickspost_path(@kickspost.user, @kickspost, display: "picture")%>
    </div>
  </div>
</div>
<div class="container post-main">
  <% unless params[:display] == "picture" %>
    <ul>
      <%= render partial: @kickspost,
                 locals: { comment_disnum: nil,
                           post_page: false } %>
      <%= render partial: @comments,
                 locals: { kickspost: @kickspost,
                           comment_disnum: nil,
                           list: nil,
                           post_page: true } %>
    </ul>
  <% else %>
    <%= render partial: 'kicksposts/kickspost_picture',
               locals: { kickspost: @kickspost,
                         comment_disnum: nil } %>
  <% end %>
</div>
<% if logged_in? %>
  <div class="content-nspace fixed-space fixed-space-bottom">
    <div class="fixed fixed-bottom">
      <%= render partial: 'comments/comment_form',
                 locals: { kickspost: @kickspost } %>
    </div>
  </div>
<% end %>