config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/latest",         to: "static_pages#latest"
  get "/follow",         to: "static_pages#follow"
  get "/follow/square",  to: "static_pages#follow_square"
  get "/help",           to: "static_pages#help"
  get "/about",          to: "static_pages#about"
  get "/terms",          to: "static_pages#terms"
  get "/privacy",        to: "static_pages#privacy"
  get "/test",           to: "static_pages#test"

  get  "/signup",   to: "users#new"
  post "/signup",   to: "users#create"
  get "/admusrind", to: "users#admusrind"

  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/auth/:provider/callback", to: "sessions#omniauth_create"

  get   "/welcome",    to: "settings#welcome"
  patch "/welcome",    to: "settings#welcome_update"
  put   "/welcome",    to: "settings#welcome_update"

  get  "/upload", to: "kicksposts#new"
  post "/upload", to: "kicksposts#create"

  get "/search", to: "searches#search"

  post   "/postcomments",    to: "comments#create"
  delete "/postcomment/:id", to: "comments#destroy",
                             as: "postcomment"

  resource :password_reset, except: [:show, :destroy],
                            path_names: { new: "" } do
    collection do
      get :confirm
    end
  end

  resource :contact, only: [:new],
                     path_names: { new: "" } do
    collection do
      post "/confirm", to: "contacts#sub_create"
      post "/",        to: "contacts#create"
      get  :confirm,
           :thanks
    end
  end

  resource   :notice,     only: [:show, :create, :destroy]
  resources  :goods,      only: [:create, :destroy]
  

  resources :users, param: :mysize_id,
                    only: [:index, :show, :destroy] do
    member do
      resources :kicksposts, except: [:new, :create, :index]

      get :following,
          :followers,
          :good
    end
  end

  resources :kicksposts, :comments, only: :none do
    get :gooders, on: :member
  end

  resources :relationships, only: [:create, :destroy]

  resource :settings, only: :none do
    get   "/option",   to: "settings#option"
    get   "/account",  to: "settings#account"
    get   "/profile",  to: "settings#profile"
    patch "/profile",  to: "settings#profile_update"
    put   "/profile",  to: "settings#profile_update"
    get   "/email",    to: "settings#email"
    patch "/email",    to: "settings#email_update"
    put   "/email",    to: "settings#email_update"
    get   "/mysizeid", to: "settings#mysizeid"
    patch "/mysizeid", to: "settings#mysizeid_update"
    put   "/mysizeid", to: "settings#mysizeid_update"
    get   "/password", to: "settings#password"
    patch "/password", to: "settings#password_update"
    put   "/password", to: "settings#password_update"
    get   "/leave",    to: "settings#leave"
    delete "/leave",   to: "settings#destroy"
  end

  # Engine to open mails in the browser
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :logged_in_user

  def welcome
  end

  def welcome_update
    current_user.validate_shoesize = true
    current_user.validate_name = true

    if twitter_linked? && current_user.update_attributes(profile_params)
      flash[:success] = "プロフィール登録が完了しました！"
      redirect_to latest_path
    elsif !twitter_linked? && current_user.update_attributes(omniauth_params)
      flash[:success] = "アカウント登録が完了しました！"
      redirect_to latest_path
    else
      current_user.reload if name_or_mysize_id_blank?
      render 'welcome'
    end
  end

  def option
  end

  def account
  end

  def profile
  end

  def profile_update
    current_user.validate_shoesize = true
    current_user.validate_name = true

    if current_user.update_attributes(profile_params)
      flash[:success] = "更新が完了しました！"
      redirect_to current_user
    else
      current_user.reload if params[:user][:name].blank?
      render 'profile'
    end
  end

  def email
  end

  def email_update
    if current_user.update(email_params)
      flash[:success] = "メールアドレスの更新に成功しました！"
      redirect_to account_settings_path
    else
      current_user.reload
      render 'email'
    end
  end

  def mysizeid
  end

  def mysizeid_update
    if current_user.update(mysizeid_params)
      flash[:success] = "MysizeIDの更新に成功しました！"
      current_user.reload
      redirect_to account_settings_path
    else
      current_user.reload
      render 'mysizeid'
    end
  end

  def password
  end

  def password_update
    current_user.validate_password = true
    
    if current_user.update_attributes(password_params)
      flash[:success] = "Passwordの変更が完了しました！"
      redirect_to account_settings_path
    else
      render 'password'
    end
  end

  def leave
  end

  def destroy
    if current_user.authenticate(params[:password]) && !current_user.admin?
      log_out
      current_user.destroy
      flash[:success] = "退会処理が完了しました。<br>ご利用ありがとうございました。"
      redirect_to root_url
    else
      flash[:danger] = (current_user.admin? ? "このアカウントは削除できません。" : "Passwordが間違っています。" )
      render 'leave'
    end
  end

  private

  def omniauth_params
    params.require(:user).permit(:name, :mysize_id, :size, :image, :image_cache)
  end

  def profile_params
    params.require(:user).permit(:name, :size, :image, :image_cache, :content)
  end

  def email_params
    params.require(:user).permit(:email)
  end

  def mysizeid_params
    params.require(:user).permit(:mysize_id)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def name_or_mysize_id_blank?
    params[:user][:name].blank? || params[:user][:mysize_id].blank?
  end

  def twitter_linked?
    current_user.uid.nil?
  end
end

app/helpers/settings_helper.rb
module SettingsHelper

  #スニーカーサイズ表
  def size_array
    ary = []
    17.times do |n|
      ary << ["#{21.5+0.5*(n+1)}cm", 21.5+0.5*(n+1)]
    end
    ary
  end

  def brand_array
    ary = [
      ["Adidas(アディダス)", "Adidas(アディダス)"],
      ["Asics(アシックス)", "Asics(アシックス)"],
      ["Converse(コンバース)", "Converse(コンバース)"],
      ["New Balance(ニューバランス)", "New Balance(ニューバランス)"],
      ["Nike(ナイキ)", "Nike(ナイキ)"],
      ["Puma(プーマ)", "Puma(プーマ)"],
      ["Reebok(リーボック)", "Reebok(リーボック)"],
      ["Vans(バンズ)", "Vans(バンズ)"]
    ]
    
  end
end

app/views/settings/_omniauth_form.html.erb
<%= form_for(current_user, url: welcome_path, multipart: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="label-form">
    <label for="user_name"><span class="font-accent">*</span>ユーザー名</label>
  </div>
  <div class="base-form">
    <%= f.text_field :name, placeholder: "(例) 靴好き男" %>
  </div>
  <div class="label-form">
    <%= f.label :mysize_id, "*Mysize ID" %>
  </div>
  <div class="base-form">
    <%= f.text_field :mysize_id, placeholder: "a-z,0-9,_ 15文字以内" %>
  </div>
  <div class="set-form clear">
    <div class="upload-form">
      <div class="label-form file-label">
        <%= f.label :image, "アイコン" %>
      </div>
      <div class="file-form">
        <%= f.label :image, class: "upload-button" do %>
          <div class="upload-icon">
            <%= fa_icon(current_user.image.blank? ? "plus" : "refresh") %>
          </div>
          <div class="preview">
            <% if current_user.image.present? %>
              <%= image_tag(image_url(current_user), alt: current_user.name, class: "cover") %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="base-form hidden-form">
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
    </div>
    <div class="size-form">
      <div class="label-form select-label font-mini">
        <label for="user_size"><span class="font-accent">*</span>スニーカーのベースサイズ</label>
      </div>
      <div class="base-form select-form">
        <%= f.select(:size, options_for_select(size_array, current_user.size)) %>
        <div class="c select-icon"><%= fa_icon("chevron-down") %></div>
      </div>
    </div>
  </div>
  <div class="c button button-mini accent">
    <%= f.submit yield(:button_text), data: { disable_with: "処理中..."} %>
  </div>
  <script type="text/javascript">
    $('#user_image').bind('change', function() {
      var size_in_megabytes = this.file[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('ファイルは最大5MBまでとなります。');
      }
    });
  </script>
<% end %>

app/views/settings/_profile_form.html.erb
<%= form_for(current_user, url: yield(:post_url), multipart: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="label-form">
    <label for="user_name"><span class="font-accent">*</span>ユーザー名</label>
  </div>
  <div class="base-form">
    <%= f.text_field :name, placeholder: "(例) 靴好き男" %>
  </div>
  <div class="set-form clear">
    <div class="upload-form">
      <div class="label-form file-label">
        <%= f.label :image, "アイコン" %>
      </div>
      <div class="file-form">
        <%= f.label :image, class: "upload-button" do %>
          <div class="upload-icon">
            <%= fa_icon(current_user.image.blank? ? "plus" : "refresh") %>
          </div>
          <div class="preview">
            <% if current_user.image.present? %>
              <%= image_tag(image_url(current_user), alt: current_user.name, class: "cover") %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="base-form hidden-form">
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
    </div>
    <div class="size-form">
      <div class="label-form select-label font-mini">
        <label for="user_size"><span class="font-accent">*</span>スニーカーのベースサイズ</label>
      </div>
      <div class="base-form select-form">
        <%= f.select(:size, options_for_select(size_array, current_user.size)) %>
        <div class="c select-icon"><%= fa_icon("chevron-down") %></div>
      </div>
    </div>
  </div>
  <div class="label-form">
    <%= f.label :content, "プロフィール" %>
  </div>
  <div class="base-form base-form-area">
    <%= f.text_area :content, class: "autoheight text-area",
        placeholder: "具体的なスニーカーのサイズ例や簡単な自己紹介などを記入しましょう(160文字以内)
(例)Jordan1(27cm)/StanSmith(26.5cm)/好きなブランドなど..." %>
  </div>
  <div class="c button button-mini accent">
    <%= f.submit yield(:button_text), data: { disable_with: "処理中..."} %>
  </div>
  <script type="text/javascript">
    $('#user_image').bind('change', function() {
      var size_in_megabytes = this.file[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('ファイルは最大5MBまでとなります。');
      }
    });
  </script>
<% end %>

app/views/settings/account.html.erb
<% provide(:title, "アカウント設定") %>
<% provide(:og_title, "アカウント設定") %>
<% provide(:og_url, account_settings_url) %>
<%= render 'layouts/back', back_path: "#{option_settings_path}" %>
<%= render 'layouts/center_header', header_text: "アカウント設定" %>

<div class="container content-nspace">
  <div class="setting-select">
    <ul>
      <li class="set-list">
        <a href="<%= mysizeid_settings_path %>">
          <div class="set-text">
            <p>MysizeID</p>
            <div class="sss"><%= "@" + current_user.mysize_id %></div>
          </div>
          <div class="set-icon">
            <%= fa_icon("angle-right") %>
          </div>
        </a>
      </li>
      <li class="set-list">
        <a href="<%= email_settings_path %>">
          <div class="set-text">
            <p>メールアドレス</p>
            <div class="sss"><%= current_user.email %></div>
          </div>
          <div class="set-icon">
            <%= fa_icon("angle-right") %>
          </div>
        </a>
      </li>
      <li class="set-list">
        <a href="<%= password_settings_path %>">
          <div class="set-text set-text1">
            <p>パスワード</p>
          </div>
          <div class="set-icon">
            <span><%= fa_icon("angle-right") %></span>
          </div>
        </a>
      </li>
    </ul>
  </div>
  <% unless current_user.admin? %>
    <div class="set-leave">
      <%= link_to "退会する", leave_settings_path %>
    </div>
  <% end %>
</div>

app/views/settings/email.html.erb
<% provide(:title, "メールアドレス編集") %>
<% provide(:og_title, "メールアドレス編集") %>
<% provide(:og_url, email_settings_url) %>
<%= render 'layouts/back', back_path: "#{account_settings_path}" %>
<%= render 'layouts/center_header', header_text: "メールアドレス編集" %>

<div class="container content-space">
  <div class="form">
    <%= form_for(current_user, url: email_settings_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="c base-form">
        <%= f.email_field :email, placeholder: "メールアドレス" %>
      </div>
      <div class="c button button-mini accent">
        <%= f.submit "保存", data: { disable_with: "処理中..."} %>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/leave.html.erb
<% provide(:title, "退会") %>
<% provide(:og_title, "退会") %>
<% provide(:og_url, leave_settings_url) %>
<%= render 'layouts/back', back_path: "#{account_settings_path}" %>

<div class="container content-space">
  <div class="page-title">
    <h1 class="title-text">Mysizeから退会する</h1>
  </div>
  <% unless current_user.admin? %>
    <div class="text">
      <p>退会すると全ての投稿や質問などが削除され、復帰することはできません。</p>
    </div>
    <div class="form">
      <%= form_tag('/settings/leave', method: "delete") do %>
        <%= render 'shared/error_messages', object: current_user %>
        <div class="label-form">
          <%= label_tag :password, "パスワード" %>
        </div>
        <div class="base-form">
          <%= password_field_tag :password, nil, placeholder: "Password" %>
        </div>
        <div class="text">
          <p>※退会処理には時間がかかる場合がございます。退化処理が完了するまで画面を閉じずにお待ちください。</p>
        </div>
        <div class="c button button-mini accent">
          <%= submit_tag "退会する", data: { disable_with: "処理中...",
                                           confirm: "退会します。取り消せませんがよろしいですか？"} %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="c">このアカウントは削除できません。</p>
  <% end %>
</div>

app/views/settings/mysizeid.html.erb
<% provide(:title, "MysizeID編集") %>
<% provide(:og_title, "MysizeID編集") %>
<% provide(:og_url, mysizeid_settings_url) %>
<%= render 'layouts/back', back_path: "#{account_settings_path}" %>
<%= render 'layouts/center_header', header_text: "MysizeID編集" %>

<div class="container content-space">
  <div class="form">
    <%= form_for(current_user, url: mysizeid_settings_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="c base-form">
        <%= f.text_field :mysize_id, placeholder: "MysizeID (a-z,0-9,_ 15文字以内)" %>
      </div>
      <div class="c button button-mini accent">
        <%= f.submit "保存", data: { disable_with: "処理中..."} %>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/option.html.erb
<% provide(:title, "オプション") %>
<% provide(:og_title, "オプション") %>
<% provide(:og_url, option_settings_url) %>
<%= render 'layouts/back', back_path: "#{user_path(current_user)}" %>
<%= render 'layouts/center_header', header_text: "オプション" %>

<div class="container content-nspace">
  <div class="setting-select">
    <ul>
      <li class="set-list">
        <a href="<%= account_settings_path %>">
          <div class="set-text set-text1">
            <p>アカウント設定</p>
          </div>
          <div class="set-icon">
            <%= fa_icon("angle-right") %>
          </div>
        </a>
      </li>
      <li class="set-list">
        <a href="<%= new_contact_path %>">
          <div class="set-text set-text1">
            <p>お問い合わせ</p>
          </div>
          <div class="set-icon">
            <span><%= fa_icon("angle-right") %></span>
          </div>
        </a>
      </li>
      <li class="set-list">
        <a href="<%= terms_path %>">
          <div class="set-text set-text1">
            <p>利用規約</p>
          </div>
          <div class="set-icon">
            <span><%= fa_icon("angle-right") %></span>
          </div>
        </a>
      </li>
      <li class="set-list">
        <a href="<%= privacy_path %>">
          <div class="set-text set-text1">
            <p>プライバシーポリシー</p>
          </div>
          <div class="set-icon">
            <span><%= fa_icon("angle-right") %></span>
          </div>
        </a>
      </li>
      <li class="set-list">
        <a href="<%= about_path %>">
          <div class="set-text set-text1">
            <p>Mysizeとは</p>
          </div>
          <div class="set-icon">
            <span><%= fa_icon("angle-right") %></span>
          </div>
        </a>
      </li>
      <li class="set-list">
        <a href="https://twitter.com/mysize_sneakers">
          <div class="set-text set-text1">
            <p>公式ツイッター</p>
          </div>
          <div class="set-icon">
            <span><%= fa_icon("angle-right") %></span>
          </div>
        </a>
      </li>
      <% if current_user.admin? %>
        <li class="set-list">
          <a href="<%= admusrind_url %>">
            <div class="set-text set-text1">
              <p>管理者ページ</p>
            </div>
            <div class="set-icon">
              <span><%= fa_icon("angle-right") %></span>
            </div>
          </a>
        </li>
      <% end %>
      <li class="set-list">
        <a rel="nofollow" data-method="delete" href="<%= logout_path %>">
          <div class="set-text set-text1">
            <p>ログアウト</p>
          </div>
          <div class="set-icon">
            <%= fa_icon("angle-right") %>
          </div>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/settings/password.html.erb
<% provide(:title, "Password編集") %>
<% provide(:og_title, "Password編集") %>
<% provide(:og_url, password_settings_url) %>
<%= render 'layouts/back', back_path: "#{account_settings_path}" %>
<%= render 'layouts/center_header', header_text: "Password編集" %>

<div class="container content-space">
  <div class="form">
    <%= form_for(current_user, url: password_settings_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="base-form">
        <%= f.password_field :password, placeholder: "新しいPassword" %>
      </div>
      <div class="base-form">
        <%= f.password_field :password_confirmation, placeholder: "Password確認" %>
      </div>
      <div class="c button button-mini accent">
        <%= f.submit "保存", data: { disable_with: "処理中..."} %>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/profile.html.erb
<% provide(:title, "プロフィール編集") %>
<% provide(:og_title, "プロフィール編集") %>
<% provide(:og_url, profile_settings_url) %>
<% provide(:button_text, "更新") %>
<% provide(:post_url, profile_settings_path) %>
<%= render 'layouts/back', back_path: "#{user_path(current_user)}" %>
<%= render 'layouts/center_header', header_text: "プロフィール編集" %>

<div class="container content-fspace">
  <div class="form">
    <%= render 'profile_form' %>
  </div>
</div>

app/views/settings/welcome.html.erb
<% provide(:title, "Welcomeページ") %>
<% provide(:og_title, "Welcomeページ") %>
<% provide(:og_url, welcome_url) %>
<% provide(:button_text, "登録する") %>
<% provide(:post_url, welcome_path) %>
<%= render 'layouts/no_left_header' %>
<%= render 'layouts/no_right_header' %>

<div class="container content-space">
  <div class="page-title">
    <h1 class="title-text">Mysizeへようこそ！</h1>
  </div>
  <div class=" c welcome-text">
    <% if current_user.uid.nil? %>
      <p>プロフィールを設定しましょう。</p>
      <p><small>(<span class="font-accent">*</span>:必須項目)</small></p>
    <% else %>
      <p>アカウント設定しましょう。</p>
      <p><small>(*:必須項目)</small></p>
    <% end %>
  </div>
  <div class="form">
    <% if current_user.uid.nil? %>
      <%= render 'profile_form' %>
    <% else %>
      <%= render 'omniauth_form' %>
    <% end %>
  </div>
</div>